<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.3.5</version>
        <relativePath/>
    </parent>

    <groupId>com.inventory</groupId>
    <artifactId>vehicle-inventory-system</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>vehicle-inventory-system</name>
    <description>Client-server Vehicle Parts Inventory and Sales Monitoring System</description>

    <modules>
        <module>inventory-server</module>
        <module>inventory-desktop</module>
    </modules>

    <properties>
        <java.version>21</java.version>
        <javafx.version>21.0.5</javafx.version>
    </properties>
</project>
