ALTER TABLE products
    ADD COLUMN IF NOT EXISTS product_image BYTEA,
    ADD COLUMN IF NOT EXISTS product_image_type VARCHAR(80),
    ADD COLUMN IF NOT EXISTS last_restocked_date DATE;

ALTER TABLE sales
    ADD COLUMN IF NOT EXISTS receipt_type VARCHAR(30) NOT NULL DEFAULT 'DELIVERY_RECEIPT';
